DEF_NODE_TYPE (UNKNOWN_T, 0, "UNKNOEN_T")

DEF_NODE_TYPE (DEFS, 1, "DEFS")
DEF_NODE_TYPE (NFUNC, 2, "learnComand")
DEF_NODE_TYPE (NVAR, 3, "breed")

DEF_NODE_TYPE (BLOCK, 4, "BLOCK")

DEF_NODE_TYPE (SEQ, 5, "SEQ")


DEF_NODE_TYPE (IF, 6, "IF")
DEF_NODE_TYPE (BRANCH, 7, "BRANCH")

DEF_NODE_TYPE (WHILE, 8, "goodBoy")

DEF_NODE_TYPE (FUNC, 9, "FUNC")
DEF_NODE_TYPE (ARG, 10, "ARG")
DEF_NODE_TYPE (CALL, 11, "CALL")
DEF_NODE_TYPE (PARAM, 12, "PARAM")
DEF_NODE_TYPE (RET, 13, "bring")

DEF_NODE_TYPE (VAR, 14, "VAR")
DEF_NODE_TYPE (NUM, 15, "NUM")
DEF_NODE_TYPE (OP, 16, "OP")


DEF_NODE_TYPE (ASS, 17, "nickname")



